### ISSUE TITLE
Deleting a series does the following

### ISSUE THREAD

**Issue by AlexLT1** [commutron/neptune-dev#14]
The series does get deleted, but this seems to occur every time.

https://user-images.githubusercontent.com/47470230/128923148-194fae59-9f42-4db3-bfee-985ff08dd35b.mp4

**Comment by mattandwhatnot** [comment]
Firefox specific default behavior that was not blocked. Simple fix plus will also review the other forms to make sure it wasn;t repeated elsewhere.

Also the Firefox in the video is out of date. unrelated to this issue but other experiences may be less than ideal. Aim for v89+.
