### ISSUE TITLE
serial number sequence crash

### ISSUE THREAD

**Issue by AlexLT1** [commutron/neptune-dev#17]
if the serial number sequence starts high enough, adding more than the remaining numbers left till you reach more than "9999" it will crash

![20210811_083750](https://user-images.githubusercontent.com/47470230/129048414-11c77689-45be-4f93-94ad-36d40821e694.jpg)

video re-recorded on desktop, instead of chromebook

https://user-images.githubusercontent.com/47470230/129050085-42533251-532e-4701-ae6d-2ee28269ba18.MOV

**Comment by mattandwhatnot** [comment]
As the formatting is standardized and in some cases mandated by the customer rolling over into the date digits is not an option.

The possible crash causing infinite loop has been eliminated and blocking error messages have been added to the check result.
