### ISSUE TITLE
First-off can be completed without a builder

### ISSUE THREAD

**Issue by AlexLT1** [commutron/neptune-dev#18]
i used my name in the video but have tested this with other users. Only locks pass button on your user before clearing the prompt. Other users show pass option before (like normal), and after clearing the prompt.

Don't think anyone will accidentally do this.  I only noticed because i filled out the Method first, and accidentally clicked my name instead of Adam.

https://user-images.githubusercontent.com/47470230/129073398-52c30527-cf29-425a-8527-d6282a620785.mp4

**Comment by mattandwhatnot** [comment]
If all options are deselected it leaves a empty list instead of reverting back to a null state. Was an issue for build method as well

Both fixed and released
