### ISSUE TITLE
Visualization graphs with touchscreen on chrome book

### ISSUE THREAD

**Issue by AlexLT1** [commutron/neptune-dev#19]
Unable to zoom. The function to pan works. This may be present for android touch screen devices as well, unfortunately i do not have access to one that I can try it on at the moment 

https://user-images.githubusercontent.com/47470230/129836453-02590912-1731-4e8f-92f0-56dc669aacbf.MOV

**Comment by mattandwhatnot** [comment]
Unfortunately this is problem with all touchscreens. Even more unfortunate, it is a shortcoming of the Victory Charts library. It has been sighted several times by other developers but it seems Formidable does not intend to add support.

Switching chart libraries is not an option. Realistically, no time available to devise a workaround.

**Comment by AlexLT1** [comment]
That's unfortunate, but I don't think it'll be a big concern. Was the only
thing I saw that didn't behave the same on touchscreen so I thought I'd
mention it.
