### ISSUE TITLE
(Non-Urgent) Nonconformance big

### ISSUE THREAD

**Issue by AlexLT1** [commutron/neptune-dev#22]
If adding multiple nonconformances at once, if you leave a comma at the end, it will add an empty nonconformance. Example (j10,j11,j12,). It was a mistake on my part, and doesn't happen often, as this is the first time I have seen it.

**Comment by mattandwhatnot** [comment]
found issue and fixed
also found in shortage add, also fixed.

will be released with 3.9.0

(_reminder_: references can be comma **or** space **or** comma & space)
