### ISSUE TITLE
Undo ship does not work properly

### ISSUE THREAD

**Issue by 1324692893** [commutron/neptune-dev#3]
Undo button in shipping is overwritten by the "finished" text box that appears, however on very rare occasions in shows up for a brief instant. If you click it during that time it causes the board to be undone on a different process besides "pack". Example being a board that comes from wave solder will be stuck on wave inspect even though the board is marked as finished.

**Comment by 1324692893** [comment]
Also in the second view the undo button appears to be disabled, even for me as shipper

**Comment by mattandwhatnot** [comment]
code error. fix in next release
