### ISSUE TITLE
Unable to export using export button

### ISSUE THREAD

**Issue by RJLeonardo** [commutron/neptune-dev#31]
![export not functioning](https://user-images.githubusercontent.com/94391903/149394402-ade688b1-a65c-4949-b34a-31fb6139309d.PNG)

**Comment by mattandwhatnot** [comment]
Found a problem where some shortfall entries could have been entered with a format error that would cause them to not be displayed in the history feed and cause an error when constructing an export.

Database repair function is ready, I will be in touch for the remote update and data fix.
