### ISSUE TITLE
Overview not loading consistently 

### ISSUE THREAD

**Issue by RJLeonardo** [commutron/neptune-dev#36]
In our show-and-tell of the latest release this morning and since there have been a number of times, the overview page will not load when returning to it from another page.  One must refresh/F5 the browser to get data to load.
I was not able to replicate myself, though it took several attempts-- intermittent, therefore.  

Screen shot:
![overview not loading](https://user-images.githubusercontent.com/94391903/159783092-f8b20948-eebb-4d22-a3a6-10fd6dac2ecd.PNG)

**Comment by mattandwhatnot** [comment]
I'm not sure whats causing that. I will need to dig into it/
