### ISSUE TITLE
Data from week previous not populating

### ISSUE THREAD

**Issue by RJLeonardo** [commutron/neptune-dev#38]
Noted this morning, March week 5 is not populated in downstream metrics. 

![image](https://user-images.githubusercontent.com/94391903/161603668-e4484ec2-ca35-4902-8d50-01b5fc4826cc.png)

Last data populated seems to be from week 13 (March 21-25).  Here is what we seen in week 14,

![image](https://user-images.githubusercontent.com/94391903/161603783-c4311c79-283d-4373-a40c-b005c8ea5a4e.png)

**Comment by mattandwhatnot** [comment]
Odd occurrence to have zero completed work orders in a week but confirmed data is accurate, no completed work orders between March 27 and April 2.
