### ISSUE TITLE
Possible bug of duplicate time entry

### ISSUE THREAD

**Issue by RJLeonardo** [commutron/neptune-dev#47]
Taylor logged into work and found that it somehow was duplicated and running at the same time. Unfortunately, she logged out and logged back in to correct the issue before we could get a screenshot of the issue or before I could see this for myself. 
I took a screenshot of the record for the sake of giving you _something_. To our knowledge, we have not encountered this before. 
This is 
![duplicate entry at same time](https://user-images.githubusercontent.com/94391903/172936906-6403f29f-f43b-456f-be93-ea81db353739.PNG)

**Comment by mattandwhatnot** [comment]
Looks similar to an issue we had more than a year ago where a work order would double start.

Logs required. 
step 1 : Have Todd enable "debug" access on your/an account, navigate to the page in the screenshot above
step 2 :  Take a new screenshot.
step 3 : Right click on the page and open "Inspect"
step 4 : Copy the entire contents of the "Console" tab and paste into a plain text document (like notepad)
step 5 : **EMAIL** me the text document and the screenshot

**Comment by RJLeonardo** [comment]
I'll pass that on. 
__________________

Just including this from an email Taylor sent to me (if of any value)
![IMG_20220609_161957](https://user-images.githubusercontent.com/94391903/173164824-8015262b-8f33-4673-8ff4-c22fedbe1328.jpg)
:

From: Taylor Spence <shadowolfxiii@gmail.com> 
Sent: Thursday, June 9, 2022 16:25
To: Robert Leonardo <robert@commutron.ca>
Subject: Glitchy Neptune

The [icon] in the upper right corner also was grayed out but I was logged in. Hollis had to remove that instance so I got relogin 
![IMG_20220609_162055](https://user-images.githubusercontent.com/94391903/173164796-209ca792-c2e6-4cb8-a279-1fecc0dd1632.jpg)

**Comment by mattandwhatnot** [comment]
Post with email from Taylor deleted because it contained personal information

**Comment by mattandwhatnot** [comment]
Unclear if the email from Taylor is about the same issue issue or another similar issue. Top _right_ button is greyed out?

**Comment by mattandwhatnot** [comment]
Likely mitigated by making start, stop, switch and edit calls with 'wait' and 'no-retry'.

Change included in version 3.11+
