### ISSUE TITLE
shipment notification

### ISSUE THREAD

**Issue by hollis242** [commutron/neptune-dev#50]
As there is a notification when the product is released to the floor, there would be customer benefits for a shipment notification as well.  The benefit would be for customers with multiple products and partial shipments of the products.  The MRP platform isn't reliable for the notifications as once was thought.

**Comment by mattandwhatnot** [comment]
Would every customer that wants notifications get both notifications? Or would it need to be customized per customer?

**Comment by hollis242** [comment]
Customized per customer.

**Comment by mattandwhatnot** [comment]
indefinitely shelved by Robert
