### ISSUE TITLE
Processes are becoming locked even with permissions.

### ISSUE THREAD

**Issue by 1324692893** [commutron/neptune-dev#6]
Example: click off hand solder inspect. The next process of testing may become locked, or when you scan another board at hand solder inspect it will become locked

Doesn't matter what inspection you click off. Doesn't matter the product. 

Two ways of bypassing this temporarily are to refresh the page, or to scan another board and go back to the previous. If you need a better example or explanation let me know

**Comment by mattandwhatnot** [comment]
yeesh, that should have been caught by QA. Found the issue. Fix released today (Monday).

**Comment by mattandwhatnot** [comment]
Stale state as prop. combined with too aggressive memo function
