### ISSUE TITLE
When choosing a process to clock into, under production activity it occasionally is listed as “false”

### ISSUE THREAD

**Issue by AlexLT1** [commutron/neptune-dev#9]
![image](https://user-images.githubusercontent.com/47470230/118054414-71e5d300-b343-11eb-8bf7-aa9486b097b4.png)

Using the edit function restores it to what it was initially supposed to be. Discovered by Jordan

**Comment by mattandwhatnot** [comment]
Thanks I completely missed that. Easy fix though; just a minor oversight in the task select input.

Initial task select value is `false`, but if select is changed to any other option then back to blank the value is recorded as `"false"`

Next release (likely 3.2.0) will include fixed form validation and db repair for the previously recorded errors.
